# Usa la imagen oficial de Node con una versión específica
FROM node:16

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo package.json e instala las dependencias
COPY package.json .

# Instala las dependencias
RUN npm install

# Copia todos los archivos de la aplicación al contenedor
COPY . .

# Construye la aplicación
RUN npm run build

# Expone el puerto 80 del contenedor
EXPOSE 80

# Comando para ejecutar la aplicación
CMD ["npm", "start"]
